### ISSUE TITLE
Issue-测试打包

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#12]
Automated Review Comments
Issues in vite.config.ts:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
