### ISSUE TITLE
Issue-新增退出接口哦

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#14]
Automated Review Comments
Issues in .env.production:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src/api/user/index.ts:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
Issues in src/store/user.ts:
  - (1, 'Hardcoded string found')
  - (3, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
