### ISSUE TITLE
Issue-公告管理完成开发

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#18]
Automated Review Comments
Issues in src/api/billboardManager/index.ts:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
Issues in src/api/billboardManager/types.ts:
  - (5, 'Line exceeds 80 characters')
Issues in src/components/LanguageInput.vue:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
Issues in src/components/ReIcon/src/offlineIcon.ts:
  - (1, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in src/views/billboardManager/component/ConfirmDialog.vue:
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
Issues in src/views/billboardManager/component/SearchForm.vue:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
Issues in src/views/billboardManager/component/TableColumnList.tsx:
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
Issues in src/views/billboardManager/form.vue:
  - (5, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (59, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
Issues in src/views/billboardManager/index.vue:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
Issues in src/views/billboardManager/utils/hook.tsx:
  - (2, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
Issues in src/views/billboardManager/utils/rule.ts:
  - (1, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (38, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
