### ISSUE TITLE
Issue-修改白名单

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#20]
Automated Review Comments
Issues in locales/json/en.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (293, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (315, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (325, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (336, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (341, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (356, 'Hardcoded string found')
  - (357, 'Hardcoded string found')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (364, 'Line exceeds 80 characters')
  - (367, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (372, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Hardcoded string found')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (384, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (388, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (391, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (394, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (403, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (414, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (418, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Line exceeds 80 characters')
  - (422, 'Hardcoded string found')
  - (425, 'Hardcoded string found')
  - (426, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (428, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
Issues in locales/json/fr.json:
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
Issues in locales/json/zh-CN.json:
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
Issues in src/api/systemConfig/index.ts:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
Issues in src/api/tenant/index.ts:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
Issues in src/api/tenant/types.ts:
  - (83, 'Line exceeds 80 characters')
Issues in src/components/ReIcon/src/offlineIcon.ts:
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
Issues in src/layout/components/sidebar/breadCrumb.vue:
  - (10, 'Hardcoded string found')
Issues in src/layout/components/sidebar/sidebarItem.vue:
  - (4, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
Issues in src/layout/index.vue:
  - (3, 'Hardcoded string found')
Issues in src/router/utils.ts:
  - (16, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
Issues in src/utils/formatNumber.ts:
  - (2, 'Line exceeds 80 characters')
Issues in src/utils/getTableWidth.ts:
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
Issues in src/utils/http/index.ts:
  - (7, 'Hardcoded string found')
Issues in src/utils/utilFn.ts:
  - (9, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
Issues in src/views/billboardManager/form.vue:
  - (7, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in src/views/roleManager/component/RoleTree.vue:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/views/systemConfig/dictManager/component/SearchForm.vue:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
Issues in src/views/systemConfig/dictManager/component/TableColumnList.tsx:
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in src/views/systemConfig/dictManager/form.vue:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
Issues in src/views/systemConfig/dictManager/index.vue:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
Issues in src/views/systemConfig/dictManager/utils/hook.tsx:
  - (6, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
Issues in src/views/systemConfig/dictManager/utils/map.ts:
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (225, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
