### ISSUE TITLE
Issue-修改登录验证逻辑

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#24]
Automated Review Comments
Issues in src/components/ResetDialog/index.vue:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
Issues in src/views/billboardManager/index.vue:
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/views/login/index.vue:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in src/views/login/utils/rule.ts:
  - (17, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (45, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
