### ISSUE TITLE
Issue-新增维护状态

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#38]
Automated Review Comments
Issues in src/api/systemConfig/index.ts:
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
Issues in src/views/systemConfig/maintainManager/index.vue:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/views/systemConfig/maintainManager/utils/hook.tsx:
  - (4, 'Hardcoded string found')
  - (20, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
