### ISSUE TITLE
Issue-优化总控系统

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#46]
Automated Review Comments
Issues in src/components/ResetDialog/index.vue:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/layout/components/navbar.vue:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in src/layout/components/sidebar/horizontal.vue:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (77, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
