### ISSUE TITLE
Issue-pro发版

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#52]
Automated Review Comments
Issues in .env.development:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/views/roleManager/component/TableColumnList.tsx:
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in src/views/roleManager/form.vue:
  - (11, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in src/views/roleManager/utils/hook.tsx:
  - (11, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in src/views/userManager/form.vue:
  - (3, 'Hardcoded string found')
Issues in src/views/userManager/index.vue:
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (37, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
