### ISSUE TITLE
Issue-调整请求线路

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#56]
Automated Review Comments
Issues in .env.development:
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in src/utils/http/index.ts:
  - (3, 'Hardcoded string found')
Issues in src/views/login/index.vue:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
