### ISSUE TITLE
Issue-修改管理员输入限制

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#58]
Automated Review Comments
Issues in .env.development:
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in src/views/tenantManager/tenantConfig/form.vue:
  - (3, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
