### ISSUE TITLE
Issue-系职能白名单配置

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#60]
Automated Review Comments
Issues in src/views/tenantManager/tenantConfig/utils/hook.tsx:
  - (6, 'Hardcoded string found')
Issues in src/views/tenantManager/tenantConfig/utils/rule.ts:
  - (2, 'Hardcoded string found')
Issues in src/views/tenantManager/whiteManager/form.vue:
  - (5, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
