### ISSUE TITLE
Issue-新增IP地址加白内容

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/kmgames-management-back-stage#66]
Automated Review Comments
Issues in src/views/clientManager/venueAccessControl/ipWhitelist/index.vue:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (44, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
